"""Assemble the context pack as text so a freshness check can compare bytes."""

import csv
import io
from pathlib import Path

from scripts.context.lib.boundaries import all_violations, violations_touching
from scripts.context.lib.complexity import CAP, function_scores
from scripts.context.lib.guards import guard_rows
from scripts.context.lib.imports import absolute_imports, imported_modules, module_name, python_files
from scripts.context.lib.paths import PACK_DIR, REPO, RULES_PACK, SRC
from scripts.context.lib.spine import all_spine, spine_touching

MARGIN = 4
IMPORTS = "imports.csv"
HOTSPOTS = "hotspots.csv"
GUARDS = "guards.csv"
INDEX = "index.md"
PACK_FILES = (GUARDS, HOTSPOTS, IMPORTS, INDEX)
RULES_LABEL = ".grok/rules/context-pack.md"


def import_rows() -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for path in python_files(SRC):
        relative = path.relative_to(SRC).as_posix()
        for module in sorted(set(imported_modules(path, SRC))):
            rows.append((relative, module))
    return rows


def hotspot_rows() -> list[tuple[str, str, int, int, int]]:
    rows: list[tuple[str, str, int, int, int]] = []
    for key, score in sorted(function_scores(SRC).items()):
        headroom = CAP - score
        if headroom > MARGIN:
            continue
        path, _, symbol = key.partition("::")
        rows.append((path, symbol, score, CAP, headroom))
    return rows


def build_files() -> dict[str, str]:
    imports = import_rows()
    hotspots = hotspot_rows()
    guards = guard_rows()
    return {
        IMPORTS: _csv(["path", "imports"], [(path, module) for path, module in imports]),
        HOTSPOTS: _csv(
            ["path", "symbol", "cc", "cap", "headroom"],
            [(path, symbol, str(cc), str(cap), str(headroom)) for path, symbol, cc, cap, headroom in hotspots],
        ),
        GUARDS: _csv(["path", "summary", "tests"], list(guards)),
        INDEX: _index(imports, hotspots, guards),
    }


def write_pack(directory: Path, files: dict[str, str]) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for name, text in files.items():
        (directory / name).write_text(text, encoding="utf-8")


def rules_document(files: dict[str, str]) -> str:
    chunks = [
        "# Context pack",
        "",
        "Generated by `scripts/context/build.py`. Grok and Claude Code load this file at session start.",
        "",
    ]
    for name in (INDEX, HOTSPOTS, GUARDS, IMPORTS):
        chunks.append(f"## {name}")
        chunks.append("")
        chunks.append(files[name].rstrip("\n"))
        chunks.append("")
    return "\n".join(chunks).rstrip("\n") + "\n"


def write_rules(path: Path, files: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rules_document(files), encoding="utf-8")


def rules_diff(path: Path, files: dict[str, str]) -> list[str]:
    if not path.is_file():
        return [f"missing {RULES_LABEL}"]
    if path.read_text(encoding="utf-8") != rules_document(files):
        return [RULES_LABEL]
    return []


def pack_diff(files: dict[str, str] | None = None) -> list[str]:
    built = build_files() if files is None else files
    return freshness_diff(PACK_DIR, built) + rules_diff(RULES_PACK, built)


def freshness_diff(directory: Path, files: dict[str, str]) -> list[str]:
    diffs: list[str] = []
    for name, text in sorted(files.items()):
        path = directory / name
        if not path.is_file():
            diffs.append(f"missing {name}")
            continue
        if path.read_text(encoding="utf-8") != text:
            diffs.append(name)
    if directory.is_dir():
        known = set(files)
        extras = sorted(path.name for path in directory.iterdir() if path.is_file() and path.name not in known)
        if extras:
            diffs.append("extra " + ", ".join(extras))
    return diffs


def pack_status() -> str:
    diff = pack_diff()
    if not diff:
        return "matches"
    return "differs: " + ", ".join(diff)


def layer_of(relative: str) -> str:
    if relative == "composition.py":
        return "composition"
    return relative.split("/", 1)[0]


def report_for(path: Path) -> str | None:
    resolved = path.resolve()
    try:
        repo_relative = resolved.relative_to(REPO).as_posix()
    except ValueError:
        return None
    lines = [f"path: {repo_relative}"]
    if _within(resolved, SRC):
        lines.extend(_production_lines(resolved))
    elif repo_relative.startswith("docs/context/") or repo_relative == RULES_LABEL:
        lines.append("layer: generated-pack")
        lines.append("owner: scripts/context/build.py")
    elif repo_relative.startswith("tests/"):
        lines.append("layer: tests")
    else:
        lines.append("layer: outside-production")
    lines.append("pack: " + pack_status())
    return "\n".join(lines) + "\n"


def who_imports(target: str, *, transitive: bool) -> str:
    module = _as_module(target)
    owners = _module_owners()
    reverse = _reverse_graph(owners)
    seen = _closure(module, reverse) if transitive else {module}
    files: set[str] = set()
    for path in _scanned_files():
        hits = _imports_of(path)
        if any(_matches_any(item, seen) for item in hits):
            files.add(path.resolve().relative_to(REPO).as_posix())
    header = module + (" transitive" if transitive else "")
    body = [header, *[f"  {item}" for item in sorted(files)]]
    if not files:
        body.append("  none")
    return "\n".join(body) + "\n"


def _production_lines(path: Path) -> list[str]:
    relative = path.relative_to(SRC).as_posix()
    lines = [f"layer: {layer_of(relative)}", "imports:"]
    imports = sorted(set(imported_modules(path, SRC)))
    lines.extend([f"  {item}" for item in imports] or ["  none"])
    lines.append("importers:")
    text = who_imports(module_name(path, SRC), transitive=False)
    importers = [line for line in text.splitlines()[1:] if line != "  none"]
    lines.extend(importers or ["  none"])
    lines.append("hotspots:")
    spots = [row for row in hotspot_rows() if row[0] == relative]
    if spots:
        lines.extend(f"  {symbol} cc={cc} headroom={headroom}" for _path, symbol, cc, _cap, headroom in spots)
    else:
        lines.append(f"  none within {MARGIN} of the cap")
    lines.append("boundary:")
    hits = violations_touching(path)
    lines.extend([f"  {item}" for item in hits] or ["  clean"])
    lines.append("spine:")
    spine_hits = spine_touching(path)
    lines.extend([f"  {item}" for item in spine_hits] or ["  clean"])
    return lines


def _index(
    imports: list[tuple[str, str]],
    hotspots: list[tuple[str, str, int, int, int]],
    guards: list[tuple[str, str, str]],
) -> str:
    closest = ["| headroom | cc | path |", "| --- | --- | --- |"]
    for path, symbol, cc, _cap, headroom in sorted(hotspots, key=lambda row: (row[4], row[0], row[1])):
        closest.append(f"| {headroom} | {cc} | {path}::{symbol} |")
    if len(closest) == 2:
        closest.append("| | | none |")
    layers = sorted({layer_of(path) for path, _module in imports})
    violations = all_violations()
    boundary = "clean" if not violations else f"{len(violations)} violation(s)"
    spine_hits = all_spine()
    spine = "clean" if not spine_hits else f"{len(spine_hits)} violation(s)"
    lines = [
        "# Context pack",
        "",
        "Generated by `scripts/context/build.py`. The fitness suite compares these bytes to a fresh build.",
        "The same build writes `.grok/rules/context-pack.md`, which Grok and Claude Code load at session start.",
        "",
        "## Caps",
        "",
        f"Cyclomatic cap is {CAP}. Headroom is that cap minus the score from "
        "`scripts/context/lib/complexity.py`. This table and `tests/fitness/test_complexity.py` call that function.",
        "",
        f"Rows here are functions within {MARGIN} of the cap, or past it.",
        "",
        "## Closest to the cap",
        "",
        *closest,
        "",
        "## Files",
        "",
        f"- `{IMPORTS}` — {len(imports)} production import edges.",
        f"- `{HOTSPOTS}` — {len(hotspots)} functions within {MARGIN} of the cap.",
        f"- `{GUARDS}` — {len(guards)} fitness modules.",
        "",
        "## Layers",
        "",
        ", ".join(layers) if layers else "none",
        "",
        f"Boundary collectors report {boundary}.",
        f"Spine collectors report {spine}.",
        "",
    ]
    return "\n".join(lines)


def _csv(header: list[str], rows: list[tuple[str, ...]]) -> str:
    buffer = io.StringIO(newline="")
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(header)
    writer.writerows(rows)
    text = buffer.getvalue()
    if not text.endswith("\n"):
        text += "\n"
    return text


def _within(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
    except ValueError:
        return False
    return True


def _as_module(target: str) -> str:
    text = target.strip().rstrip("/")
    if text.endswith(".py") or "/" in text:
        candidate = Path(text)
        if not candidate.is_absolute():
            candidate = REPO / candidate
        resolved = candidate.resolve()
        if _within(resolved, SRC):
            return module_name(resolved, SRC)
    if text == "fs_prod_agent" or text.startswith("fs_prod_agent."):
        return text
    return f"fs_prod_agent.{text}"


def _module_owners() -> dict[str, str]:
    owners: dict[str, str] = {}
    for path in python_files(SRC):
        owners[module_name(path, SRC)] = path.relative_to(SRC).as_posix()
    return owners


def _reverse_graph(owners: dict[str, str]) -> dict[str, set[str]]:
    reverse: dict[str, set[str]] = {name: set() for name in owners}
    for path in python_files(SRC):
        source = module_name(path, SRC)
        for module in imported_modules(path, SRC):
            for owner in owners:
                if module == owner or module.startswith(owner + "."):
                    reverse.setdefault(owner, set()).add(source)
    return reverse


def _closure(start: str, reverse: dict[str, set[str]]) -> set[str]:
    seen = {start}
    stack = [start]
    while stack:
        current = stack.pop()
        for parent in reverse.get(current, ()):
            if parent in seen:
                continue
            seen.add(parent)
            stack.append(parent)
    return seen


def _scanned_files() -> list[Path]:
    roots = [SRC, REPO / "tests", REPO / "scripts"]
    files: list[Path] = []
    for root in roots:
        if root.is_dir():
            files.extend(python_files(root))
    return files


def _imports_of(path: Path) -> list[str]:
    if _within(path, SRC):
        return imported_modules(path, SRC)
    return absolute_imports(path)


def _matches_any(module: str, targets: set[str]) -> bool:
    return any(module == target or module.startswith(target + ".") for target in targets)
